Cooking/Models/DinnerDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cooking.Models
{
    public class DinnerDto
    {
        public string name { get; set; }

    }
}

Cooking/Models/LunchDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cooking.Models
{
    public class LunchDto
    {
        public string name { get; set; }

    }
}

Cooking/Models/ResturantDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cooking.Models
{
    public class ResturantDto
    {
        public string name { get; set; }
    }
}

Cooking/Controllers/DinnerController.cs
using Cooking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooking.Controllers
{
    public class DinnerController : Controller
    {
        // GET: Lunch
        public ActionResult Index()
        {

            DinnerDto model = new DinnerDto();
            model.name = "Dinner";


            return View(model);

        }

    }
}

Cooking/Controllers/HomeController.cs
using Cooking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "cooking.";
            ResturantDto model = new ResturantDto();
            model.name = "Cat cafe";
            return View(model);
        }
        public ActionResult test()
        {
            ViewBag.Message = "cooking.";
            ResturantDto model = new ResturantDto();
            model.name = "Cat cafe";
            return View(model);
        }



        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }

    }
}

Cooking/Controllers/LunchController.cs
using Cooking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooking.Controllers
{
    public class LunchController : Controller
    {
        // GET: Lunch
        public ActionResult Index()
        {

            LunchDto model = new LunchDto();
            model.name = "Lunch";
          

            return View(model);

        }

    }
}

Cooking/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooking.Controllers
{
    public class RecipeController : Controller
    {
        // GET: Breakfast
        public ActionResult Breakfast()
        {
            return View();
        }
    }
}

Cooking/Views/Dinner/Index.cshtml
@model Cooking.Models.DinnerDto

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dinner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
             
           )

                (<table style="width:100%">
                    <tr>
                        <th><img src="~/Food_Photo/Mushroompasta.jpg" alt="Mushroompasta" width="400" height="500"></th>
                        <th><img src="~/Images/breakfast board.jpg" alt="breakfast board" width="400" height="500"></th>
                    </tr>
                    <tr>
                        <td>BC Catfffeinated: French Dark Roasted Coffee</td>
                        <td>Garfields Breakfast: </td>
                    </tr>
                </table>
                

            </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    
}

<div>
    @Html.ActionLink("Back to Top", "Index")
</div>

Cooking/Views/Home/About.cshtml
@model Cooking.Models.ResturantDto


@{
    ViewBag.Title = "About";
}



<p>Welcome to my resturant @Model.name</p>
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<h4>Coffee</h4>



<img src="~/Images/coffee.jpg" alt="coffee" width="400" height="500">

<p>test</p>

<img src="~/Images/breakfast board.jpg" alt="breakfast board" width="400" height="500">

<p>Broc</p>

<img src="~/Images/broc.jpg" alt="breakfast board" width="400" height="500">

Cooking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Cooking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>A&L Cooking </h1>
    <p class="lead">This is a list of our homeade meals!</p>


    <!--<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>-->
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Kitchen Tools</h2>
        <p>
           Keep up to date on the latest tools to make your cooking experience not just easier but more enjoyable.
        </p>
        <p><a class="btn btn-default" href="https://www.amazon.com/s?k=cooking+utensils+amazon+basics&sprefix=cooking+utensils+amazon+%2Caps%2C104&ref=nb_sb_ss_ts-doa-p_1_24">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Pantry Essentials</h2>
        <p>The nessessary pantry items to make sure you never run out of ingredients for your favorite meals.</p>
        <p><a class="btn btn-default" href="https://www.foodnetwork.com/recipes/packages/cooking-from-the-pantry/pantry-essentials-checklist">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Quick Snacks</h2>
        <p>Perfect for family parties, or just for yourself to enjoy.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Cooking/Views/Home/test.cshtml
@model Cooking.Models.ResturantDto

@{
    ViewBag.Title = "test";
}

<h2>test</h2>

<div>
    <h4>ResturantDto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cooking/Views/Lunch/Index.cshtml
@model Cooking.Models.LunchDto

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <h4>LunchDto</h4>
    <hr />
    <dl class="dl-horizontal">

        <th><img src="~/Images/RedPasta.jpg" alt="coffee" width="400" height="500"></th>
        <th><img src="~/Images/TofuBowl.jpg" alt="TofuBowl" width="400" height="500"></th>



        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cooking/Views/Recipe/Breakfast.cshtml
@{
    ViewBag.Title = "breakfast";
}


<h2>Breakfast</h2>
<h3 style="color:sienna;">
    This is a paragraph.</>
</h3>

<table style="width:100%">
    <tr>
        <th><img src="~/Images/coffee.jpg" alt="coffee" width="400" height="500"></th>
        <th><img src="~/Images/breakfast board.jpg" alt="breakfast board" width="400" height="500"></th>
    </tr>
    <tr>
        <td>BC Catfffeinated: French Dark Roasted Coffee</td>
        <td>Garfields Breakfast: </td>
    </tr>


</table>

<br>

<table style="width:100%">
    <tr>
        <th><img src="~/Images/coffee.jpg" alt="coffee" width="400" height="500"></th>
        <th><img src="~/Images/breakfast board.jpg" alt="breakfast board" width="400" height="500"></th>

    </tr>
</table>



<div>
    @Html.ActionLink("Back to Top", "breakfast")
</div>

Cooking/Views/Recipe/Lunch.cshtml
@{
    ViewBag.Title = "Lunch";
}

<h2>Lunch</h2>
<h3>coffee</h3>

<table style="width:100%">
    <tr>
        <th><img src="~/Images/coffee.jpg" alt="coffee" width="400" height="500"></th>
        <th><img src="~/Images/breakfast board.jpg" alt="breakfast board" width="400" height="500"></th>
    </tr>
    <tr>
        <td>BC Catfffeinated: French Dark Roasted Coffee</td>
        <td>Garfields Breakfast: </td>
    </tr>
</table>

Cooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<link href="~/Content/Cooking.css" rel="stylesheet" />
</head>
<body> 
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Menu <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Breakfast", "Breakfast", "Recipe")</li>
                            <li>@Html.ActionLink("Lunch", "Index", "Lunch")</li>
                            <li>@Html.ActionLink("Dinner", "Index", "Dinner")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>